# This is only needed for compatibility with Ubuntu 22, newer systems use the
# pyproject.toml
[metadata]
name = perfact-dbutils
description = Basic tools for interacting with the database
long_description = file: README.md
long_description_content_type = text/markdown
license = GPL-2.0-or-later
author = Viktor Dick
author_email = viktor.dick@perfact.de
classifiers =
    Programming Language :: Python :: 3
    Operating System :: POSIX :: Linux
    Topic :: Database

[options]
packages = find_namespace:
python_requires = >=3.10
install_requires =
    psycopg2
use_scm_version = True
setup_requires =
    setuptools_scm
include_package_data = False

[options.packages.find]
include =
    perfact.*

[bdist_wheel]
universal = 1
