[tox]
envlist = py3
isolated_build = True

[pytest]

[testenv]
deps =
    flake8
    pytest
    pytest-cov
    coverage
    psycopg[c]
    psycopg2
    types-psycopg2
    pytest-postgresql
    bandit
    mypy
    sphinx
    sphinx-rtd-theme

commands =
    flake8 perfact
    bandit --configfile bandit.yaml -r perfact
    pytest --doctest-modules --cov-branch --cov=perfact --cov-fail-under=100 --cov-report=term-missing {posargs}
    mypy perfact

[testenv:docs]
commands =
  sphinx-apidoc -o doc/source/api perfact */tests/* -f -M -e --ext-coverage --implicit-namespaces
  sphinx-build -W -b html doc/source doc/build/html
  sphinx-build -W -b man doc/source doc/build/man
