[tox]
envlist = py3

[pytest]

[testenv]
deps =
    flake8
    pytest
    coverage
    psycopg[c]
    pytest-postgresql

commands =
    flake8 perfact
    coverage run --source=perfact -m pytest {posargs}
    coverage report --show-missing
