[tox]
envlist = py3
isolated_build = True

[pytest]

[testenv]
deps =
    flake8
    pytest
    pytest-cov
    coverage
    psycopg[c]
    pytest-postgresql
    bandit
    mypy
    sphinx

commands =
    flake8 perfact
    bandit --configfile bandit.yaml -r perfact
    pytest --doctest-modules --cov-branch --cov=perfact --cov-fail-under=100 {posargs}
    mypy perfact
    coverage report --show-missing

[testenv:docs]
commands =
  sphinx-apidoc -o doc/source/api perfact */tests/* -f -M -e --ext-coverage --implicit-namespaces
  sphinx-build -W -b html doc/source doc/build/html
