name: Build Package
on:
  push:
    branches:
      - 'main'
  pull_request: {}

jobs:
  build:
    strategy:
      matrix:
        # target: ['ubuntu:jammy', 'debian:bookworm', 'debian:trixie']
        target: ['trixie']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true
    - uses: jtdor/build-deb-action@v1
      with:
        docker-image: docker.io/perfact/build-${{ matrix.target }}
